### ISSUE TITLE
NSNegateBooleanTransformerName

### ISSUE THREAD

**Issue by markohlebar** [markohlebar/BIND#18]
BINDT(self.viewModel, booleanProperty , ~>, self, other.booleanProperty, NSNegateBooleanTransformerName)

causes:
-[__NSCFConstantString transformedValue:]: unrecognized selector sent to instance 0x7fd34b395700

**Comment by markohlebar** [comment]
@spagosx this works now.

**Comment by spagosx** [comment]
@markohlebar  Lovely!!
